### PR TITLE
feat: add release ci

### PR DESCRIPTION
**Pull request by anbraten**

### CODE REVIEW

**Comment by lukashass** [comment]
@anbraten This will not work because you did not use conventional commits for c771a3ec97aae02d61946b988602888e4dcd0378 and 57033b26cd0fb71ae4fecc927938e8223470f31b :facepalm: 

Maybe you could fix them by force push?

**Comment by raphaelschwinger** [comment]
> @anbraten This will not work because you did not use conventional commits for [c771a3e](https://github.com/geprog/use-feathers/commit/c771a3ec97aae02d61946b988602888e4dcd0378) and [57033b2](https://github.com/geprog/use-feathers/commit/57033b26cd0fb71ae4fecc927938e8223470f31b) 🤦
> 
> Maybe you could fix them by force push?

I will make a new PR with revert commits for them and new ones with correct names, then we just have to merge them normally and not squash them. This seems to be a bit cleaner for me.

**Comment by raphaelschwinger** [comment]
@anbraten @lukashass see #23

**Comment by anbraten** [comment]
> @anbraten @lukashass see #23

@lukashass @raphaelschwinger I did a dry-run locally and it should be fine to squash this PR. 

```console
yarn run v1.22.5
$ semantic-release --dry-run
[2:18:55 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.4
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[2:18:56 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[2:18:57 PM] [semantic-release] › ⚠  Run automated release from branch release on repository https://[secure]@github.com/geprog/use-feathers in dry-run mode
[2:18:58 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[2:18:58 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[2:18:58 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[2:18:59 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[2:18:59 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[2:18:59 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[2:18:59 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[2:18:59 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[2:18:59 PM] [semantic-release] › ℹ  Found git tag v0.0.1 associated with version 0.0.1 on branch release
[2:18:59 PM] [semantic-release] › ℹ  Found 1 commits since last release
[2:18:59 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[2:18:59 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: add release ci
[2:18:59 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[2:18:59 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: minor release
[2:18:59 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[2:18:59 PM] [semantic-release] › ℹ  The next release version is 0.1.0
[2:18:59 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:18:59 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:18:59 PM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/npm" in dry-run mode
[2:18:59 PM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/changelog" in dry-run mode
[2:18:59 PM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/git" in dry-run mode
[2:18:59 PM] [semantic-release] › ⚠  Skip v0.1.0 tag creation in dry-run mode
[2:18:59 PM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/npm" in dry-run mode
[2:18:59 PM] [semantic-release] › ✔  Published release 0.1.0 on release channel
[2:18:59 PM] [semantic-release] › ℹ  Release note for version 0.1.0:
# 0.1.0 (2021-07-08)

### Features

    * add release ci (6fcddcd)

Done in 4.35s.

```

`semantic-release` simply skips none conventional commits. We only have to use cc it in the future. For example by merging #23.

**Review by raphaelschwinger — APPROVED** [review]
LGTM!

**Pull request merged**
