### PR TITLE
chore: reset package version

### PR DESCRIPTION
**Pull request by anbraten**

### CODE REVIEW

**Comment by raphaelschwinger** [comment]
@anbraten have you "dry-run" it? Will the first version be then 0.0.1? Is that okay since we already published 0.1.0?

**Comment by anbraten** [comment]
> @anbraten have you "dry-run" it? Will the first version be then 0.0.1? Is that okay since we already published 0.1.0?

@raphaelschwinger Just tested it. `semantic-releases` uses some different way of gathering the current version. It wont ever change the version inside the `package.json` in our repo anyways. It only sets the correct version before releasing to npm.

**Comment by raphaelschwinger** [comment]
@anbraten Whats the version number in npm  then?

**Comment by anbraten** [comment]
> @anbraten Whats the version number in npm then?

@raphaelschwinger  You can see the current version at [npmjs.com](https://www.npmjs.com/package/@geprog/use-feathers). ATM it is `0.1.1`.  The npm page is linked on the repositories main page as well.

**Comment by raphaelschwinger** [comment]
@anbraten Yes, but will this PR affect this ?

**Comment by anbraten** [comment]
@raphaelschwinger It wont change anything. I just did it for documentation purpose as I saw other repositories setting the version to that. As this does not change the source-code it wont increase the version.

**Review by raphaelschwinger — APPROVED** [review]

**Pull request merged**
